coqc Lib/Normalization.v
coqc Lib/Algebra.v
coqc Lib/EqDec.v
coqc Lib/LinearOrder.v
coqc Lib/HoTT.v
coqc Lib/Sorted.v
coqc Lib/MergeSort.v
coqc Extras/Permutations.v
coqc Extras/Streicher.v
coqc Lib/Deduplicated.v
coqc Lib/DedupSort.v